main: me.screescree.doorlock.DoorLock
name: DoorLock
description: Adds a fully functional door lock system, with keys that can be used to lock and unlock doors.
version: 1.0
author: screescree
api-version: 1.18

commands:
  createkey:
    description: "Creates a key for the door you are looking at. You may only do this if the door does not already have a key created by someone else for it."
    usage: "§cUsage: /<command> [<amount>]"
    permission: "doorlock.createkey"

permissions:
  doorlock.createkey:
    description: "Allows players to create a key for a door."
    default: true

  doorlock.admin:
    description: "Allows the user to use the plugin's admin features."
    default: op
    children:
      doorlock.admin.createkey: true
      doorlock.admin.bypasslocks: true

  doorlock.admin.createkey:
    description: "Allows players to create a key for a door, regardless of whether the door already has a key created by someone else for it."
    default: op
  doorlock.admin.bypasslocks:
    description: "Allows players to bypass the lock of all doors."
    default: op